### ISSUE TITLE
Formatting not working with latest IntelliJ 2025.3 and Java 25

### ISSUE THREAD

**Issue by Srivastava295** [MrDolch/external-java-formatter-intellij-plugin#77]
I get the following error when I apply formatting.

`Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.Queue com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()' at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:367) at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:335) at com.google.googlejavaformat.java.JavaInput. (JavaInput.java:277) at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:254) at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:241) at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:75) at com.google.googlejavaformat.java.Main.formatStdin(Main.java:224) at com.google.googlejavaformat.java.Main.format(Main.java:128) at com.google.googlejavaformat.java.Main.main(Main.java:92) at com.google.googlejavaformat.java.Main.main(Main.java:82) at com.google.googlejavaformat.java.Main.main(Main.java:71)`
